name: Publish Front-end and Back-end on Netlify and Heroku
on: 
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'npm'
        cache-dependency-path: root/package-lock.json
    - run: npm ci
    - run: npm test
    - run: npm run build
    - name: Publishing the Front
      uses: netlify/actions/build@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
