name: Easy Integration for Node.js
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'npm'
    - run: npm ci
      working-directory: ./root
    - run: npm test
      working-directory: ./root
    - run: npm run build
      working-directory: ./root
    